### ISSUE TITLE
Missing usage documentation

### ISSUE THREAD

**Issue by Andy2244** [darkfeline/animanager-go#3]
I can't figure out how to actually use the manager, maybe a short help or how to setup the config could explain things?

I mainly get this error:
`Error loading config: load config: open .animanager\config.toml: The system cannot find the path specified.`

Btw does animanager-go also hash files for lookup?

**Comment by darkfeline** [comment]
I'm currently working on docs.  Short intro:

I'm assuming you're familiar with command line.  If not, Animanager is probably not for you.

You need to create a config file as the error mentions.  Animanager wasn't written to support Windows specifically so the configuration may seem odd.  Example file:

```
database = "$HOME/.animanager/database.db"
player = ["mpv", "--profile=default"]
watch_dirs = ["/path/to/video/files", "/more/files"]
```

Run `animanager search` to find shows.

Run `animanager add` to add shows by ID.

Run `animanager register` to add a regexp pattern to recognize which files are for the show.

Run `animanager findfiles` to find files for registered shows.  Usually you set up a cronjob to run this on a schedule.

Run `animanager watchable` to show which shows are watchable (have files for the next unwatched episode).

Run  `animanager watch` to watch the next episode using the configured player.

**Comment by Andy2244** [comment]
Still not sure if animanager uses the UDP api for file hashing/searching?

**Comment by darkfeline** [comment]
Animanager doesn't use the UDP API.  I plan on adding it sometime since it's more reliable than regexp matching, but it's low priority because the existing logic works pretty well already.  I made Animanager because I wanted to spend less time tracking watched shows/episodes and more time actually watching anime, and as it is now, it fulfills that goal.

**Comment by Andy2244** [comment]
Sure np, was just curious.
Atm i test for Shoko replacements, so i tested all the clients/cli stuff i could find on AniDB/github. There are not this many left that actually have commits in 2019/2020, so most tools are either abandoned or clunky to use.
